### 角色增删改查
@baseUrl = http://localhost:6001

### 获取所有角色
GET {{baseUrl}}/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDNjNDM5YmNlY2VkMTM1OWZlMTg5ZCIsImlhdCI6MTY0ODYwOTkxNiwiZXhwIjoxNjQ4OTY5OTE2fQ.r_HRNGm9L_ARze7w_HULSvzmZfGThpOnimM1Dommj5Y

### 添加用户角色
POST {{baseUrl}}/roles/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmQ2NjMwZTBlZDc2OTg1MDY4ZjliNCIsImlhdCI6MTY0NzE0ODk2MywiZXhwIjoxNjQ3NTA4OTYzfQ.dplWHi3A6TJyDTJkoQQe1s3Q7z-8zxm9QZY52wxqxmo

{
  "role_name": "运营",
  "description": "运营人员"
}

### 编辑角色
POST {{baseUrl}}/roles/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmQ2NWFhYTI4YWRlOTM0MzZiZjVmMiIsImlhdCI6MTY0NzUyNzE4NiwiZXhwIjoxNjQ3ODg3MTg2fQ._BfWKAjsu59kBX_KsjbGHISoTnIczkmqEzspHtFq2d4

{
  "id": "622d80b9236d4401cda4fc17",
  "role_name": "医务人员"
}

### 删除角色
POST {{baseUrl}}/roles/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmQ2NWFhYTI4YWRlOTM0MzZiZjVmMiIsImlhdCI6MTY0NzUyNzE4NiwiZXhwIjoxNjQ3ODg3MTg2fQ._BfWKAjsu59kBX_KsjbGHISoTnIczkmqEzspHtFq2d4

{
  "id": "62333899a160ee910b11e17f"
} 

### 获取权限列表
GET {{baseUrl}}/roles/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDNjNDM5YmNlY2VkMTM1OWZlMTg5ZCIsImlhdCI6MTY0ODYwOTkxNiwiZXhwIjoxNjQ4OTY5OTE2fQ.r_HRNGm9L_ARze7w_HULSvzmZfGThpOnimM1Dommj5Y

### 获取菜单栏
GET {{baseUrl}}/roles/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDNjNDM5YmNlY2VkMTM1OWZlMTg5ZCIsImlhdCI6MTY0ODYwOTkxNiwiZXhwIjoxNjQ4OTY5OTE2fQ.r_HRNGm9L_ARze7w_HULSvzmZfGThpOnimM1Dommj5Y

### 获取登录时角色菜单
POST {{baseUrl}}/roles/authMenu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDNjNDM5YmNlY2VkMTM1OWZlMTg5ZCIsImlhdCI6MTY0ODYwOTkxNiwiZXhwIjoxNjQ4OTY5OTE2fQ.r_HRNGm9L_ARze7w_HULSvzmZfGThpOnimM1Dommj5Y

{
  "id": "6243c68a670c4371234e7d74"
}

### 角色授权
POST {{baseUrl}}/roles/doAuth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDNjNDM5YmNlY2VkMTM1OWZlMTg5ZCIsImlhdCI6MTY0ODYwOTkxNiwiZXhwIjoxNjQ4OTY5OTE2fQ.r_HRNGm9L_ARze7w_HULSvzmZfGThpOnimM1Dommj5Y

{
  "id": "6243c68a670c4371234e7d74",
  "menu_node": [
    "6243c570670c4371234e7d72",
    "6243c62b670c4371234e7d73",
    "6243cddc670c4371234e7d77"
  ]
}

### 查询当前角色权限
POST {{baseUrl}}/roles/curAuth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmQ2NWFhYTI4YWRlOTM0MzZiZjVmMiIsImlhdCI6MTY0NzY1ODc2MSwiZXhwIjoxNjQ4MDE4NzYxfQ.D5lj-NXw-v7V8ZrGX6IdseBJB4jz_QyV6U2qgXQM2Rw

{
  "id": "6243c68a670c4371234e7d74"
}